### PR TITLE
Add composer-smaller-lock

### PR DESCRIPTION
**Pull request by kubawerlos**
Hi @realodix,

after the fix https://github.com/kubawerlos/composer-smaller-lock/pull/4 everything should be fine now.

### CODE REVIEW

**Comment by realodix** [comment]
Hi @kubawerlos, but apparently still making unwanted problem

**Comment by kubawerlos** [comment]
I see, 2nd fix in the way: https://github.com/kubawerlos/composer-smaller-lock/pull/5

**Comment by realodix** [comment]
Install v0.1.3
https://github.com/realodix/urlhub/runs/2840913268

**Comment by kubawerlos** [comment]
@realodix this time I've tested locally (the trick was to remove `vendor` dir after adding `composer-smaller-lock` and all should be fine now.

**Comment by realodix** [comment]
Thank you 👍

**Pull request merged**
