### PR TITLE
Slim skeleton

### PR DESCRIPTION
**Pull request by realodix**

### CODE REVIEW

**Comment by lionslair** [comment]
How messy are you finding this upgrade?

**Comment by realodix** [comment]
What makes it look messy?

**Comment by lionslair** [comment]
No not the work. The upgrade. A lot has been pulled out. I got 50 projects to eventually update at work and the removing all the files from the structure to slim makes me nervous

**Comment by realodix** [comment]
Maybe the reason why it looks so messy is because I merged an update to write code for the new controller that follows the guidelines in the Laravel 11 documentation.

**Pull request merged**
