### PR TITLE
feat: add docker support

### PR DESCRIPTION
**Pull request by Jorgelig**
The Docker integration helps the development environment a lot. Support was implemented to build the project in a docker container to avoid problems with dependencies and make it compatible with multiple operating systems in the development environment.

image
image

### CODE REVIEW

**Comment by Jorgelig** [comment]
@realodix The Docker integration helps the development environment a lot. What do you think?

**Comment by Jorgelig** [comment]
@realodix any update?

**Comment by realodix** [comment]
Thanks for your pull request to UrlHub!

Unfortunately, I'm going to delay merging this code for now. Feel free to add this to your own app

**Comment by mqu** [comment]
hello ; Docker support is really missing for UrlHub application !

**Pull request closed without merging**
